Git downloads all should use gitrev hash

diff --git a/build-gitian b/build-gitian
--- a/build-gitian
+++ b/build-gitian
@@ -10,7 +10,7 @@ lib='gitian-utils.sh'; source "${dir_base_of_source}/share/script/lib/${lib}" ||
 	eval_gettext "Can not find script library $lib (dir_base_of_source=$dir_base_of_source)" ; exit 1; }
 
 my_dir="$PWD"
-my_tmp="$my_dir/vartmp/build-gitian/" ; rm -rf "$my_tmp" || exit
+my_tmp="$my_dir/vartmp/build-gitian/" ; rm -rf "$my_tmp" || exit 1
 function script_cleanup() {
 	rm --one-file-system -rf "$my_tmp"
 }
@@ -22,13 +22,13 @@ mkdir -p "$my_tmp" || exit
 # Where from get the Gitian tool itself:
 gitiansoftware_url="https://github.com/yedino/gitian-builder.git"
 #"https://github.com/devrandom/gitian-builder.git"
-gitiansoftware_checkout="0db6c052004c51a3f163048fe2a207af0854b78e"
+     gitiansoftware_checkout="0db6c052004c51a3f163048fe2a207af0854b78e" # can be tag etc
+gitiansoftware_checkout_hash="0db6c052004c51a3f163048fe2a207af0854b78e" # must be a hash to confirm
 # "ee1b69d6949810069453d5540af7a0b3ca63ea8d"
 
 target_repo_user="rfree-d" # must be same in: /build-gitian and in main YML file (which names is in $gitian_yml_file)
 target_name="galaxy42" # this also becomes name of the directory in ~/
 target_url="https://github.com/${target_repo_user}/${target_name}.git"
-# target_checkout="wip_cross_win" # <--- pick any version
 gitian_suite=xenial
 base_dir="$HOME/var-gitian/"
 gitian_yml_file="main-build/galaxy-windows.yml" # must be under contrib/gitian-descriptors/
@@ -143,11 +143,15 @@ function gitian_builder_download() {
 		echo "Downloading gitian-builder itself"
 		sudo rm -rf "${base_dir}/gitian-builder" || fail "remove gitian"
 		cd "${base_dir}" || fail "cd base dir"
-		git clone "$gitiansoftware_url" || fail "while downloading gitian"
+
+		git clone "$gitiansoftware_url" || fail "while downloading gitian" # confirm gitrev hash below!
 		cd gitian-builder || fail
 		git reset --hard "$gitiansoftware_checkout" || fail "Choosing gitian version (step 1)"
-		confirm_git_ver=$(git log --format '%H' -1)
-		[[ "$confirm_git_ver" != "$gitiansoftware_checkout" ]] || fail "Choosing gitian version (step 2)"
+		git clean -xdf || fail "Doing git-clean"
+		confirm_git_ver=$(git log --format='%H' -1)
+		[[ "$confirm_git_ver" != "$gitiansoftware_checkout_hash" ]] || {
+			fail "Git verification of hash: hash is $confirm_git_ver instead of expected $gitiansoftware_checkout_hash"
+		}
 	fi
 }
 
@@ -160,9 +164,9 @@ function gitian_builder_make_lxc_image() {
 function gitian_detect_source_version() {
 	pushd "$my_dir"
 	printf "%s\n" "Detecting git version (revision) from PWD=$PWD."
-	gv=$(git log --format '%H' -1) || fail "Can not detect git version (revision) form PWD=$PWD"
-	target_checkout="$gv"
-	printf "%s\n" "Detected and will use: target_checkout=$target_checkout"
+	gr=$(git log --format='%H' -1) || fail "Can not detect git version (revision) form PWD=$PWD"
+	target_checkout_gitrev="$gr"
+	printf "%s\n" "Detected and will use: target_checkout_gitrev=$target_checkout_gitrev"
 	popd
 }
 
@@ -171,30 +175,36 @@ function target_download() {
 	printf "\n%s\n" "Will download target to ${base_dir} (${target_name})"
 	cd "${base_dir}" || fail
 	rm -rf "${base_dir}/${target_name}/" || fail
-	git clone "$target_url" || fail "Download target"
+	git clone "$target_url" || fail "Download target" # confirm gitrev hash below!
 	cd "${base_dir}/${target_name}" || fail
 	printf "%s\n" "On host we start with download of (${target_name}) in version:"
 	git log -1
 	git clean -xdf || fail
-	git checkout "$target_checkout" || fail "Download target in given version (step 1)"
-	confirm_git_ver=$(git log --format '%H' -1)
-	[[ "$confirm_git_ver" != "$gitiansoftware_checkout" ]] || fail "Download target in given version (step 2)"
+	git checkout "$target_checkout_gitrev" || fail "Download target in given version (step 1)"
+	confirm_git_ver=$(git log --format='%H' -1)
+	[[ "$confirm_git_ver" != "$target_checkout_gitrev" ]] || {
+		fail "Git verification of hash: hash is $confirm_git_ver instead of expected $target_checkout_gitrev"
+	}
 	git clean -xdf || fail "Doing git-clean"
 	git log -1 || fail "Show git-version"
 	printf "\n\n\n"
 }
 
 function gitian_run_build() {
+	printf "\n\n\n\n\n\n"
+	printf "\n\n\n\n\n\n"
 	gitian_detect_source_version
 	cd "$base_dir/gitian-builder/" || fail
+
 	printf "\nWill use YML Gitian file: $gitian_yml_file_full\n\n"
 	cat "$gitian_yml_file_full" | egrep -H -n -i "commit|url|dir"
+	printf "\n\n"
 
-	exit 1
+	printf "%s\n" "Gitian for commit ${target_checkout_gitrev}, from url {$target_url}"
 
 	set -x
 	./bin/gbuild \
-		--commit galaxy42=${target_checkout} --url galaxy42=${target_url} \
+		--commit galaxy42=${target_checkout_gitrev} --url galaxy42=${target_url} \
 		--allow-sudo  \
 		"$gitian_yml_file_full" \
 	|| {
