Gitian: gitrev on-target path fix

diff --git a/build-gitian b/build-gitian
--- a/build-gitian
+++ b/build-gitian
@@ -229,21 +229,22 @@ function get_host_info() {
 }
 
 function gitian_show_result() {
+	printf "\n\n\n%s\n" "Will show results now (base_dir=$base_dir)"
 	cd "${base_dir}/gitian-builder" || fail "cd dir of gitian-builder" # need it to call on-target
-	info_gitian=$(cd "${base_dir}/gitian-builder/" ; git log -1 | head -n 1 | cut -d' ' -f2 | head -c 8)
-	info_target=$(cd "${base_dir}/${target_name}/" ; git log -1 | head -n 1 | cut -d' ' -f2 | head -c 999)
-	info_binary=$(on-target /home/ubuntu/build/galaxy42/contrib/tools/results-of-build-windows.sh)
+	info_gitian=$(cd "${base_dir}/gitian-builder/" ; git log -1 | head -n 1 | cut -d' ' -f2 | head -c 8) || fail "Info git gitian-builder"
+	info_target=$(cd "${base_dir}/${target_name}/" ; git log -1 | head -n 1 | cut -d' ' -f2 | head -c 999) || fail "Info target"
+	info_binary=$(on-target /home/ubuntu/build/galaxy42/contrib/tools/results-of-build-windows.sh) || fail "Info binary results win"
 	info_binary_first=$( printf "$info_binary" | head -n 1 )
-	info_host="$(get_host_info)"
+	info_host="$(get_host_info)" || fail "Info host"
 	# info_target_yml=$( python3 ${my_dir}/contrib/gitian-tools/get_version_from_yaml.py  "$gitian_yml_file_full" | cut -d' ' -f1 | head -c 8 )
-	target_in_gitian_gitrev=$( on-target /home/ubuntu/build/galaxy42/contrib/tools/my-gitian-gitrev.sh  )
+	target_in_gitian_gitrev=$( on-target /home/ubuntu/build/galaxy42/contrib/tools/my-gitian-gitrev.sh  ) || fail "Info on-target gitian rev"
 	info_target_commit="${target_in_gitian_gitrev}"
 	info_target_commit_name="${info_target_commit}"
 	if [[ "$info_target_commit_name" == "$info_target" ]] ; then info_target_commit="(same hash)" ; fi
 
 	echo "Script ${info_thisscript} using Gitian ($info_gitian) of $target_name $info_target ($info_target_commit_name) gives $info_binary_first on $info_host"
 
-	echo "Report (from inside Gitian):"
+	echo "Report (received from inside Gitian):"
 	echo "$info_binary"
 }
 
