Gitin: DNS install +lang (ok?)

diff --git a/build-gitian b/build-gitian
--- a/build-gitian
+++ b/build-gitian
@@ -22,6 +22,11 @@ init_platforminfo || { printf "%s\n" "$(gettext "error_init_platforminfo")" ; ex
 target_name="galaxy42" # will be asserted when detecting git repo url. this also becomes name of the directory in ~/
 # target_repo_user , target_url will be auto detected
 
+function fail() {
+	echo "Error occured (in $0) will exit: " "$@"
+	exit 1
+}
+
 my_dir="$PWD"
 my_tmp="$my_dir/vartmp/build-gitian/" ; rm -rf "$my_tmp" || exit 1
 function script_cleanup() {
@@ -124,11 +129,6 @@ function set_env() {
 
 	export GITIAN_HOST_IP=10.0.3.2
 	export LXC_GUEST_IP=10.0.3.5
-}
-
-function fail() {
-	echo "Error occured, will exit ($1)"
-	exit 1
 }
 
 function setup_host_for_lxc() {
