[fix] debootstrap no need to fix

diff --git a/build-gitian b/build-gitian
--- a/build-gitian
+++ b/build-gitian
@@ -45,15 +45,29 @@ cd "$base_dir" || fail "Can not enter the base dir ($base_dir)"
 #set -x
 
 function fix_template_script() {
-  # fix Debian Jessie (and any other distro) that lacks Xenial script/template in it's debootstrap.
-
+	# fix Debian Jessie (and any other distro) that lacks Xenial script/template in it's debootstrap.
 	# gbuild calls ---> make-base-vm (it's own script) ---> that calls debootstrap from system.
-  # debootstrap uses dir DEBOOTSTRAP_DIR=/usr/share/debootstrap to load templates.
-  # that dir contains:
+	# debootstrap uses dir DEBOOTSTRAP_DIR=/usr/share/debootstrap to load templates.
+	# that dir contains:
 	# devices.tar.gz  functions/  scripts/
-  # and the subdir scripts/ needs to have script e.g. "xenial" (when we use xenial ubuntu in our Gitian process)
-  dbs_sys="/usr/share/debootstrap"
-  [[ -r "$dbs_sys" ]] || { printf "Can not read debootstrap data dir [$dbs_sys], is debootstrap installed?\n" ; exit 1; }
+	# and the subdir scripts/ needs to have script e.g. "xenial" (when we use xenial ubuntu in our Gitian process)
+	if [[ ! -z "$buildgitian_dbs_skip_template_fix" ]] ; then printf "Skipping debootstrap template fix (due to options)\n"; return ; fi
+
+	if [[ ! -z "$buildgitian_dbs_sys" ]] ; then
+		dbs_sys="$buildgitian_dbs_sys"
+	else
+		dbs_sys="/usr/share/debootstrap" # system's location of debootstrap
+		[[ -r "$dbs_sys" ]] || {
+			printf "Warning: Can not read debootstrap data dir [$dbs_sys]\n"
+			dbs_sys="/usr/local/share/debootstrap" # other location
+			[[ -r "$dbs_sys" ]] || {
+				printf "Warning: Can not read debootstrap data dir [$dbs_sys]\n"
+				printf "Error: Debootstrap seems not installed\n" ; exit 1; # exit
+			}
+		}
+	fi
+
+	printf "Assuming debootstrap system's version data dir is dbs_sys=$dbs_sys"
 
   suite="$gitian_suite"
   rm -rf "${target_dbs}"
@@ -61,7 +75,7 @@ function fix_template_script() {
   if [[ ! -r "$dbs_sys/scripts/$suite" ]] ; then
   	echo "Your system seems to lack te debootstrap template for suite '$suite', we will work around this now."
 
-		for item_full in "${dbs_sys}"/*  ; do
+		for item_full in "${dbs_sys}"/*  ; do # link top level things, e.g. "functions/" except for scripts/
 			[[ -e "$item_full" ]] || { echo "Can not read item_full (step1) $item_full" ; exit 1 ; }
 			item="${item_full##*/}"
 			echo "(step1) item_full=$item_full item=$item"
@@ -71,18 +85,20 @@ function fix_template_script() {
 		done
 
 		mkdir "${target_dbs}/scripts"
-		for item_full in "${dbs_sys}/scripts"/*  ; do
+		for item_full in "${dbs_sys}/scripts"/*  ; do # link all scripts
 				echo "(step2) item_full=$item_full"
 				ln -s "$item_full" "${target_dbs}scripts" # link a script
 		done
 
-		# add our file:
-		cp "${my_dir}/contrib/gitian-debootstrap/scripts/xenial" $"$target_dbs/scripts/"
-	fi
+		# add our script file:
+		cp "${my_dir}/contrib/gitian-debootstrap/scripts/${suite}" $"$target_dbs/scripts/"
 
-	export DEBOOTSTRAP_DIR="$target_dbs"
-	export GITIAN_SUDO_USE_DEBOOTSTRAP_DIR="yes"
-	echo "Exporting DEBOOTSTRAP_DIR=$DEBOOTSTRAP_DIR GITIAN_SUDO_USE_DEBOOTSTRAP_DIR=$GITIAN_SUDO_USE_DEBOOTSTRAP_DIR"
+		export DEBOOTSTRAP_DIR="$target_dbs"
+		export GITIAN_SUDO_USE_DEBOOTSTRAP_DIR="yes"
+		echo "Exporting DEBOOTSTRAP_DIR=$DEBOOTSTRAP_DIR GITIAN_SUDO_USE_DEBOOTSTRAP_DIR=$GITIAN_SUDO_USE_DEBOOTSTRAP_DIR"
+	else
+		echo "Your system's debootstrap seems ready to support suite '$suite' - no need to fix anything there."
+	fi
 }
 
 function set_env() {
@@ -208,6 +224,7 @@ function special_command_on_target() {
 
 cat <<EOF
 Usage: call this program with one argument, either:
+
   install - installs everything, this will do a sudo and as root will setup it all - run it once
   image - also recreates the System Image (e.g. LXC) - run it once (as user) and then from time to time
   fast - faster gbuild, no re-creationg of System Image (e.g. LXC) - run it often
@@ -215,6 +232,9 @@ Usage: call this program with one argument, either:
   on-target - opens a bash console inside the System Image (e.g. LXC) so you can debug it here
   on-target-root - same, but you are the root user (insie System Image e.g. LXC)
 
+  Configuration options, set env variables:
+    export buildgitian_dbs_skip_template_fix=1 to skip the automatic debootstrap template fix
+    export buildgitian_dbs_sys="/some/dir" to force the debootstrap template fix to search there for it's files
 
 EOF
 
