Gitian: new lxc-net install [todo]
Test: delete OUR STUFF from /etc/rc.local,
delete all /etc/rc.local..lxc.........

run:

share/script/setup-lxc-host

with option:

1)

--normal
--all-if

RESULT:
when you run:
sudo sh /etc/rc.local...lxc....

then test:

iptables-save,
it will who one rule for any card

2)

--normal
--some-if
'eth0 eth1 eth2 eth7 wlan3'

sudo sh /etc/rc.local...lxc....

this should be in iptables-save - many rules, for this all cards one in each line

diff --git a/share/script/setup-lxc-host b/share/script/setup-lxc-host
--- a/share/script/setup-lxc-host
+++ b/share/script/setup-lxc-host
@@ -24,22 +24,22 @@ $0 --normal --all-if
 $0 --normal --some-if "eth0 eth1 eth2 eth3 eth4 wlan0 wlan1 wlan2 usb0 usb1 usb2"
 
 It should set up computer to have rules like after running for example:
-	 iptables -t nat -D POSTROUTING -j lxc-nat-v1
-	 iptables -t nat -F lxc-nat-v1
-	 iptables -t nat -X lxc-nat-v1
-	 iptables -t nat -N lxc-nat-v1
-	 iptables -t nat -I lxc-nat-v1 -o eth1 -j MASQUERADE
-	 iptables -t nat -I lxc-nat-v1 -o eth2 -j MASQUERADE
-	 iptables -t nat -I lxc-nat-v1 -o eth3 -j MASQUERADE
-	 iptables -t nat -I POSTROUTING -j lxc-nat-v1
+	iptables -t nat -D POSTROUTING -j lxc-nat-v1
+	iptables -t nat -F lxc-nat-v1
+	iptables -t nat -X lxc-nat-v1
+	iptables -t nat -N lxc-nat-v1
+	iptables -t nat -I lxc-nat-v1 -o eth1 -j MASQUERADE
+	iptables -t nat -I lxc-nat-v1 -o eth2 -j MASQUERADE
+	iptables -t nat -I lxc-nat-v1 -o eth3 -j MASQUERADE
+	iptables -t nat -I POSTROUTING -j lxc-nat-v1
 
 EOF
 
 }
 
-usage
-
-exit 1
+function fail() {
+	echo "Error: " "$@" ; exit 1
+}
 
 marker='#marker_gitian_lxc_is_added_here' # to find if initfile already has the hook calling our main autostart script
 initfile='/etc/rc.local' # put here our autostart script
@@ -47,8 +47,17 @@ initfile='/etc/rc.local' # put here our autostart script
 do_install_main=1 # do we want to install the call to mainscript
 
 opt_force_s="$1"
-opt_all_if="$2"
+opt_all_if_s="$2"
 lxc_iflist="$3"
+
+if [[ ! ( ("$opt_force_s" == "--force") || ("$opt_force_s" == "--normal" ) ) ]] ; then
+	usage
+	exit 1
+fi
+if [[ ! ( ("$opt_all_if_s" == "--all-if") || ("$opt_all_if_s" == "--some-if" ) ) ]] ; then
+	usage
+	exit 1
+fi
 
 if [ $(id -u) != 0 ]
 then
@@ -57,14 +66,15 @@ then
 fi
 
 grep "$marker" "$initfile" && {
-	printf "\nIt seems lxc setup (at least the main hook) is already installed into file [$initfile].\n\n"
+	printf "\nIt seems lxc setup (at least the main hook) is already installed into file [$initfile], good.\n\n"
 	if [[ '$1' != '--force' ]] ; then
 		printf "Will NOT install lxc setup again then.\n"
 		do_install_main=0
 	fi
 }
 
-ourscript="/etc/rc.local.lxcnet-gitian" # this script is generated here.
+ourscript="/etc/rc.local.lxcnet-gitian" # this script will be generated here, from template
+ourscript_template='share/script/rc.local.lxcnet-gitian.template' # our template
 
 if (( do_install_main )) ; then
 	name="/etc/rc.local"
@@ -80,31 +90,15 @@ if (( do_install_main )) ; then
 	echo "# start of gitian lxc (call only)" >> "$name"
 	echo "sh $ourscript" >> "$name"
 	echo "# end of gitian lxc" >> "$name"
-
-	# generate $outscript
-	echo "$marker" >> "$ourscript"
-	echo "# start of gitian lxc (script itself)" >> "$ourscript"
-	echo 'brctl addbr br0' >> "$ourscript"
-	echo 'ifconfig br0 10.0.3.2/24 up' >> "$ourscript"
-	echo "lxc_iflist='$lxc_iflist'" >> "$ourscript" # <--- here the script will have literal text like =eth0 eth1 eth2 ...
-	if [[ "$opt_all_if" == "--all-if" ]] ; then
-		echo "lxc_all=1" >> "$outscript"
-	else
-		echo "lxc_all=0" >> "$outscript"
-	fi
-	# echo '' >> "$ourscript"
-	echo 'if (( lxc_all )) ; then ' >> "$ourscript"
-	echo '  for ifname in $lxc_iflist ; do ' >> "$ourscript"
-	echo '    iptables -t nat -A POSTROUTING -o $ifname -j MASQUERADE' >> "$ourscript"
-	echo '  done' >> "$ourscript"
-	echo 'else' >> "$ourscript"
-	echo '  iptables -t nat -A POSTROUTING -j MASQUERADE' >> "$ourscript"
-	echo 'fi' >> "$ourscript"
-	echo 'echo 1 > /proc/sys/net/ipv4/ip_forward' >> "$ourscript"
-	echo "# end of gitian lxc" >> "$ourscript"
-	echo '' >> "$ourscript"
-
 fi
+
+# generate $outscript
+cp -ar "$ourscript_template" "$ourscript" || fail "copy template"
+#  fill in variables
+sed -i -e "s|__VAR_iflist|$lxc_iflist|g" "$ourscript"
+opt_all_if=0
+if [[ "$opt_all_if_s" == "--all-if" ]] ; then opt_all_if=1 ; fi
+sed -i -e "s|__VAR_lxc_all|$opt_all_if|g" "$ourscript"
 
 printf "\nInstalling sudoers settings\n"
 echo "%sudo ALL=NOPASSWD: /usr/bin/lxc-start" > /etc/sudoers.d/gitian-lxc    # new file
