Gitian: build 32 and 64 from galaxy-windows.yml

diff --git a/contrib/gitian-descriptors/main-build/galaxy-windows-script b/contrib/gitian-descriptors/main-build/galaxy-windows-script
--- a/contrib/gitian-descriptors/main-build/galaxy-windows-script
+++ b/contrib/gitian-descriptors/main-build/galaxy-windows-script
@@ -418,12 +418,13 @@ cd "$GALAXY42_DIR"
 # git clean -fdx # need submodules
 git submodule update --init --recursive
 
-
 echo "BOOST_ROOT: "$BOOST_DIR"/mingw_build "
 echo "SODIUM_ROOT: $SODIUM_ROOT"
 
-cmake -DBOOST_ROOT="$BOOST_DIR"/mingw_build -DSODIUM_ROOT_DIR="$SODIUM_ROOT" -DSODIUM_LIBRARY="$SODIUM_ROOT/lib/libsodium.dll.a" -DSODIUM_INCLUDE_DIR="$SODIUM_ROOT/include" -DTARGET_ARCH=$TARGET_ARCH -DCMAKE_TOOLCHAIN_FILE=toolchain.cmake.in -DCMAKE_BUILD_TYPE=Debug .
-make tunserver.elf
+printf "\n\nMoving on to main build of actually our project:"
+
+cmake -DBOOST_ROOT="$BOOST_DIR"/mingw_build -DSODIUM_ROOT_DIR="$SODIUM_ROOT" -DSODIUM_LIBRARY="$SODIUM_ROOT/lib/libsodium.dll.a" -DSODIUM_INCLUDE_DIR="$SODIUM_ROOT/include" -DTARGET_ARCH=$TARGET_ARCH -DCMAKE_TOOLCHAIN_FILE=toolchain.cmake.in -DCMAKE_BUILD_TYPE=Debug . || fail "cmake of our project failed"
+make tunserver.elf || fail "make of our project (main binary) failed"
 
 echo "Printing checksums:"
 sha256sum *.exe | sort
