[wip] Gitian: makensis almost working, plugin is TODO

diff --git a/contrib/gitian-descriptors/main-build/galaxy-windows-script-master b/contrib/gitian-descriptors/main-build/galaxy-windows-script-master
--- a/contrib/gitian-descriptors/main-build/galaxy-windows-script-master
+++ b/contrib/gitian-descriptors/main-build/galaxy-windows-script-master
@@ -69,16 +69,31 @@ if (( ! option_skip_cd )) ; then
 	cd "$HOME/build/galaxy42" || fail "cd to home build (in MASTER script)"
 fi
 
+# ubuntu@gitian:~/build/galaxy42$ ls contrib/nsis-installer-windows/bin/x86/  ; x64
+nsis_bin_input='./contrib/nsis-installer-windows/bin/'
+
+build="/home/ubuntu/build"
+
 if (( option_do_it_32bit )) ; then
 	export TARGET_ARCH="i686-w64-mingw32"
 	printf "\n\n%s\n" "Will build for TARGET_ARCH=$TARGET_ARCH"
 	"$script" "$@" || fail "Buil failed (for TARGET_ARCH=$TARGET_ARCH)"
+	cp "tunserver.elf.exe" "$nsis_bin_input/x86/" || fail "copy (project binaries)"
+	cp $(find $build/boost/mingw_build/  -name  '*.dll')  $(find $build/libsodium/src/libsodium/.libs/  -name  '*.dll') "$nsis_bin_input/x86/" || fail "copy (deps libs)"
+	# TODO ^ nicer bash style (arrays/escaping)
 fi
 
 if (( option_do_it_64bit )) ; then
 	export TARGET_ARCH="x86_64-w64-mingw32"
 	printf "\n\n%s\n" "Will build for TARGET_ARCH=$TARGET_ARCH"
 	"$script" "$@" || fail "Buil failed (for TARGET_ARCH=$TARGET_ARCH)"
+	cp "tunserver.elf.exe" "$nsis_bin_input/x86/" || fail "copy (project binaries)"
+	cp $(find $build/boost/mingw_build/  -name  '*.dll')  $(find $build/libsodium/src/libsodium/.libs/  -name  '*.dll') "$nsis_bin_input/x86/" || fail "copy (deps libs)"
+	# TODO ^ nicer bash style (arrays/escaping)
 fi
+
+printf "\n\nBinaries built (and results are copied) (for all selected 32/64 versions) - proceeding to NSIS.\n\n"
+
+./contrib/nsis-installer-windows/galaxy-windows-installer || fail "NSIS failed."
 
 
diff --git a/contrib/nsis-installer-windows/galaxy-windows-installer b/contrib/nsis-installer-windows/galaxy-windows-installer
--- a/contrib/nsis-installer-windows/galaxy-windows-installer
+++ b/contrib/nsis-installer-windows/galaxy-windows-installer
@@ -1,17 +1,20 @@
 #!/bin/bash
 
 
-galaxy42_dir="/path/to/yedino/galaxy42"
-
+galaxy42_dir="/home/ubuntu/build/galaxy42"
 
 # copy dll's, tunserver.elf.exe etc to contrib/nsis-installer-windows/bin  x64 x86
 
 function fail() {
-	printf "\n\nError: %s\n\n" "$*"
+	printf "\n\nError (in NSIS, $0) : %s\n\n" "$*"
 	exit 1
 }
 
 printf "\n\n\nBuilding zlib (for NSIS)\n\n\n"
+
+[[ -r "$galaxy42_dir" ]] || fail "Can not enter galaxy42_dir=[$galaxy42_dir]"
+
+if (( 0 )) ; then # XXX
 
 # build zlib
 rm -rf zlib
@@ -55,10 +58,14 @@ pushd nsis || fail
 
 popd
 
+fi
 
-# build installer
+# use the nsis tool - actually build installer of our project!
 pushd nsis/install_dir || fail
-		
-		./makensis "$galaxy42_dir/contrib/nsis-installer-windows/installer.nsi" || fail "Makensis of our project failed"
-
+	printf "\n\nPreparing to makensis in PWD=$PWD\n\n"
+	cp "$galaxy42_dir/contrib/nsis-installer-windows/plugins/NSIS_Service_Lib/servicelib.nsh" ./ || fail "copy nsis plugin here for use"
+	printf "\n\nRunning makensis in PWD=$PWD\n\n"
+	set -x
+	./makensis "$galaxy42_dir/contrib/nsis-installer-windows/installer.nsi" || fail "Makensis of our project failed"
+	set +x
 popd
