Gitian linux static: boost: testing wrappers

diff --git a/contrib/gitian-descriptors/main-build/galaxy-linux-script b/contrib/gitian-descriptors/main-build/galaxy-linux-script
--- a/contrib/gitian-descriptors/main-build/galaxy-linux-script
+++ b/contrib/gitian-descriptors/main-build/galaxy-linux-script
@@ -5,6 +5,8 @@ function fail() {
 	printf "\nERROR (in $0): " "$@" "\n"
 	exit 1
 }
+
+  GALAXY_DIR="/home/ubuntu/build/galaxy42/"
   
   REFERENCE_DATETIME="2016-08-01 00:00:00"
 
@@ -19,7 +21,7 @@ function fail() {
   ### it seems to be on MIT licence: "Bitcoin Core is released under the terms of the MIT license":
   ### https://github.com/bitcoin/bitcoin/blob/0d0abcac1efeb94f441aa13714ba01ccfacc05c0/COPYING
 
-  WRAP_DIR=$HOME/wrapped
+  WRAP_DIR="$HOME/wrapped"
 
   ##HOSTS="i686-pc-linux-gnu x86_64-linux-gnu arm-linux-gnueabihf aarch64-linux-gnu"
   HOSTS="x86_64-linux-gnu"
@@ -59,28 +61,34 @@ function fail() {
 
   function create_global_faketime_wrappers {
   for prog in ${FAKETIME_PROGS}; do
-    echo '#!/bin/bash' > ${WRAP_DIR}/${prog}
-    echo "REAL=\`which -a ${prog} | grep -v ${WRAP_DIR}/${prog} | head -1\`" >> ${WRAP_DIR}/${prog}
-    echo 'export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1' >> ${WRAP_DIR}/${prog}
-    echo "export FAKETIME=\"$1\"" >> ${WRAP_DIR}/${prog}
-    echo 'set -x' > ${WRAP_DIR}/${prog}
-    echo "\$REAL \$@" >> $WRAP_DIR/${prog}
-    echo 'set +x' > ${WRAP_DIR}/${prog}
-    chmod +x ${WRAP_DIR}/${prog}
+    out="${WRAP_DIR}/${prog}"
+    echo "" > "$out"
+    echo '#!/bin/bash' > "$out"
+    echo "REAL=\`which -a ${prog} | grep -v ${WRAP_DIR}/${prog} | head -1\`" >> "$out"
+    echo 'export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1' >> "$out"
+    echo "export FAKETIME=\"$1\"" >> "$out"
+    echo 'echo "(from $0) will use REAL=[$REAL]"' >> "$out"
+    echo 'set -x' >> "$out"
+    echo "\$REAL \$@" >> "$out"
+    echo 'set +x' >> "$out"
+    chmod +x "$out"
   done
   }
 
   function create_per-host_faketime_wrappers {
   for i in $HOSTS; do
     for prog in ${FAKETIME_HOST_PROGS}; do
-        echo '#!/bin/bash' > ${WRAP_DIR}/${i}-${prog}
-        echo "REAL=\`which -a ${i}-${prog} | grep -v ${WRAP_DIR}/${i}-${prog} | head -1\`" >> ${WRAP_DIR}/${i}-${prog}
-        echo 'export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1' >> ${WRAP_DIR}/${i}-${prog}
-        echo "export FAKETIME=\"$1\"" >> ${WRAP_DIR}/${i}-${prog}
-    	echo 'set -x' > ${WRAP_DIR}/${prog}
-        echo "\$REAL \$@" >> $WRAP_DIR/${i}-${prog}
-    	echo 'set +x' > ${WRAP_DIR}/${prog}
-        chmod +x ${WRAP_DIR}/${i}-${prog}
+	out="${WRAP_DIR}/${i}-${prog}"
+	echo "" > "$out"
+        echo '#!/bin/bash' >> "$out"
+        echo "REAL=\`which -a ${i}-${prog} | grep -v ${WRAP_DIR}/${i}-${prog} | head -1\`" >> "$out"
+        echo 'export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1' >> "$out"
+        echo "export FAKETIME=\"$1\"" >> "$out"
+        echo 'echo "(from $0) will use REAL=[$REAL]"' >> "$out"
+    	echo 'set -x' >> "$out"
+        echo "\$REAL \$@" >> "$out"
+    	echo 'set +x' >> "$out"
+        chmod +x "$out"
     done
   done
   }
@@ -104,9 +112,10 @@ function fail() {
 
   for prog in ${COMPILERS}; do
   echo "Creating writer for compiler prog=$PROG with FAKETIME=${REFERENCE_DATETIME}"
-  rm -f "${WRAP_DIR}/${prog}"
+  out="${WRAP_DIR}/${prog}"
+  rm -f "$out"
 
-cat << EOF > ${WRAP_DIR}/${prog}
+cat << EOF > "$out"
 
   #!/bin/bash
   REAL="`which -a ${prog} | grep -v ${WRAP_DIR}/${prog} | head -1`"
@@ -120,15 +129,20 @@ cat << EOF > ${WRAP_DIR}/${prog}
   done
   export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1
   export FAKETIME="${REFERENCE_DATETIME}"
-  echo "In wrapper, will call real compiler (REAL=\$REAL) with FAKETIME=\$FAKETIME, LD_PRELOAD=\$LD_PRELOAD"
-  echo 'set -x' > ${WRAP_DIR}/${prog}
+  echo "In wrapper ($0) will call real compiler (REAL=\$REAL) with FAKETIME=\$FAKETIME, LD_PRELOAD=\$LD_PRELOAD"
+  set -x
   \$REAL \$@
-  echo 'set +x' > ${WRAP_DIR}/${prog}
+  set +x
 
 EOF
 
-  chmod +x ${WRAP_DIR}/${prog}
+  chmod +x "$out"
   done
+
+
+
+
+
 
   if false ; then # TODO
   cd bitcoin
@@ -157,7 +171,23 @@ EOF
 
 
   printf "\n\n\nDoing boost static build\n\n\n"
+<<<<<<< Updated upstream
   contrib/gitian-descriptors/libboost-build/build-boost-static || fail "Failed to build dependence - static boost lib"
+=======
+  printf "\nTEST TOOLS:\n"
+  set -x
+  which ar
+  which ranlib
+  ar --version || fail "test ar failed"
+  ranlib --version || fail "test ranlib failed"
+  set +x
+  printf "\n\n"
+
+  pushd "${GALAXY_DIR}" || fail
+  contrib/gitian-descriptors/libboost-build/build-boost-static || fail "Failed to build dependence - static boost lib"
+  popd || fail
+  echo "\nAll done regarding boost.\n"
+>>>>>>> Stashed changes
 
   # *** main build starts here ***
   pushd galaxy42
