[gitian][linux] add tar and gzip as wrapped progs, + some code style

diff --git a/contrib/gitian-descriptors/main-build/galaxy-linux-script b/contrib/gitian-descriptors/main-build/galaxy-linux-script
--- a/contrib/gitian-descriptors/main-build/galaxy-linux-script
+++ b/contrib/gitian-descriptors/main-build/galaxy-linux-script
@@ -45,8 +45,8 @@ export OUTDIR
   CONFIGFLAGS="--enable-glibc-back-compat --enable-reduce-exports --disable-bench --disable-gui-tests"
   # CONFIGFLAGS=""
 
-  FAKETIME_HOST_PROGS="ar ranlib nm ld ldd"
-  FAKETIME_PROGS="date ar ranlib nm ld ldd"
+FAKETIME_HOST_PROGS="ar ranlib nm ld ldd"
+FAKETIME_PROGS="date ar ranlib nm ld ldd tar gzip"
 
   # TODO?
   HOST_CFLAGS="-O2 -g"
@@ -196,30 +196,32 @@ EOF
 # printf "\n\n=== EXITED TEST SHELL ==="
 # sleep 1 # XXX
 
-  pushd "${GALAXY_DIR}" || fail
-  contrib/gitian-descriptors/libboost-build/build-boost-static || fail "Failed to build dependence - static boost lib"
-  popd || fail
-  echo "\nAll done regarding boost.\n"
+pushd "${GALAXY_DIR}" || fail
+	contrib/gitian-descriptors/libboost-build/build-boost-static || fail "Failed to build dependence - static boost lib"
+popd || fail
 
-  # *** main build starts here ***
-  pushd galaxy42
-  echo -e "\n\nDoing the build, inside Gitian in PWD=$PWD\n\n"
+echo "\nAll done regarding boost.\n"
 
-  git clean -fdx
-  # make dist # delete
-  COVERAGE=0 EXTLEVEL=0 \
-    BUILD_STATIC=1 BUILD_SET_BOOST_ROOT="$BUILD_TOP_DIR/boost/static-build/" \
-    ./do --go || fail "Failed to do the main build of our project"
-  #############################################
+# *** main build starts here ***
+pushd galaxy42
+	echo -e "\n\nDoing the build, inside Gitian in PWD=$PWD\n\n"
 
-  echo -e "\n\nBuild is done.\n\n"
-  popd
+	git clean -fdx
+	# make dist # delete
+	COVERAGE=0 \
+	EXTLEVEL=0 \
+	BUILD_STATIC=1 \
+	BUILD_SET_BOOST_ROOT="$BUILD_TOP_DIR/boost/static-build/" \
+	./do --go \
+		|| fail "Failed to do the main build of our project"
 
+	echo -e "\n\nBuild is done.\n\n"
+popd
 
 echo -e "\n\nBuild will start the linux packer.\n"
 pushd "${GALAXY_DIR}" || fail
-echo "In PWD=$PWD"
-contrib/tools/build-pack-linux.sh || fail "Can not pack the build results"
+	echo "In PWD=$PWD"
+	contrib/tools/build-pack-linux.sh "gitian" || fail "Can not pack the build results"
 popd || fail
 
   # when we create .tgz.gz - TODO later
