[gitian] multiarch boost buil

diff --git a/contrib/gitian-descriptors/main-build/galaxy-windows-script b/contrib/gitian-descriptors/main-build/galaxy-windows-script
--- a/contrib/gitian-descriptors/main-build/galaxy-windows-script
+++ b/contrib/gitian-descriptors/main-build/galaxy-windows-script
@@ -10,10 +10,6 @@ readonly BUILD_DIR="/home/ubuntu/build/" # where deps are built
 
 readonly WRAP_DIR="$HOME/wrapped"
 
-# importing functions for boost main and submodules download
-. "${GALAXY_DIR}"/contrib/gitian-descriptors/libboost-build/dl-boost-submodules
-. "${GALAXY_DIR}"/contrib/gitian-descriptors/libboost-build/dl-boost
-
 # import another functions
 . "${GALAXY_DIR}"/share/script/lib/fail.sh
 . "${GALAXY_DIR}"/share/script/lib/create_faketime_wrappers.sh
@@ -38,26 +34,26 @@ option_verbose=0
 while getopts ":vbsSDh" opt; do
 	case $opt in
 		D)
-		echo "Skip all downloads"
-		option_download_skip=1
-		;;
+			echo "Skip all downloads"
+			option_download_skip=1
+			;;
 		v)
-		echo "Be verbose (show debug etc)"
-                option_verbose=1
-                ;;
+			echo "Be verbose (show debug etc)"
+			option_verbose=1
+			;;
 		b)
-		echo "Will Skip boost"
-                option_allow_boost=0
-                ;;
+			echo "Will Skip boost"
+			option_allow_boost=0
+			;;
 		s)
-		echo "Will Skip sodium"
-                option_allow_sodium=0
-                ;;
+			echo "Will Skip sodium"
+			option_allow_sodium=0
+			;;
 		S)
-		option_shell_in_sodium=1
-		;;
-                h)
-                cat <<EOF
+			option_shell_in_sodium=1
+			;;
+		h)
+			cat <<EOF
 
 This is the internal script to build Windows version of this project ($PROJECT_NAME).
 It should be called by Gitian, inside LXC.
@@ -79,13 +75,13 @@ Options:
 	TARGET_ARCH to x86_64-w64-mingw32 i686-w64-mingw32
 
 EOF
-                                exit 0
-                                ;;
-                        '?')
-                                printf "\n\nERROR: Unknown option, run with -h for help.\n"
-                                exit 1
-                                ;;
-          esac
+			exit 0
+			;;
+		'?')
+			printf "\n\nERROR: Unknown option, run with -h for help.\n"
+			exit 1
+			;;
+		esac
 done
 
 
@@ -172,99 +168,17 @@ printf "\nPWD=$PWD in script $0\n"
 #popd
 #printf "\n\n"
 
-## clone and build boost
-printf "\n\n=========================================================================\n\n"
-printf "boost...\n\n"
-readonly BOOST_DIR="$HOME/build/boost/"
 
-cd "$HOME/build/" || fail "Can not enter build dir"
-
-option_download_skip=0  # XXXXXXXXXXXXXXXXX
-option_allow_boost=1
-
-if (( option_allow_boost )) ; then
-    printf "\n\nWill build boost now\n\n"
-
-    if (( option_download_skip )) ; then
-        printf "\n\n\n\nSkipping download (boost)\n\n\n\n"
-
-    else
-        # Download main boost repository
-        dl_boost
-		pushd boost || fail "Can not enter build dir"
-			# Download boost submodules in n=3 attempts
-			dl_boost_submodules_n 3
-		popd
-    fi
-
-pushd boost || fail # cd
-pwd
-ls
-
-# delete it to have a clean build (even if we keept downloaded PREVIOUSLY files)
-git clean -xdf || fail
-rm -rf mingw_build || fail
-mkdir mingw_build || fail
-
-boost_user_gcc="$HOME/wrapped/$TARGET_ARCH-g++ ;"
-printf "\n\nWill set boost user config to use compiler: (%s)\n" "$boost_user_gcc"
-
-printf "\n\nBoost build - main part (PWD=$PWD). ls:\n" ; ls ; printf "\n\n"
-echo "# This config was GENERATED (will be over-written) by $0." > user-config.jam || fail
-echo "using gcc : 4.9.2 : $boost_user_gcc" >> user-config.jam || fail
-./bootstrap.sh --without-icu || fail
-
-printf "Starting the b2 boost build\n"
-set -x
-b2_opt_with_lib=( "--with-filesystem" "--with-system" "--with-program_options" "--with-thread" "--with-locale" )
-b2_opt_debug=( )
-if (( option_verbose )) ; then
-	b2_opt_debug=( "-d" "4" "--debug-building" )
-else
-	b2_opt_debug=( "-d" "0" "--debug-building" )
-fi
-
-./b2 headers
-
-./b2 \
-	"${b2_opt_debug[@]}" \
-	-a --user-config=user-config.jam toolset=gcc target-os=windows variant=release \
-	 --prefix=/"$BOOST_DIR"/mingw_build threading=multi  threadapi=win32 link=shared \
-	 "${b2_opt_with_lib[@]}" \
-	 runtime-link=shared \
-	-j 1 \
-	-sNO_BZIP2=1 --sNO_ZLIB=1 \
-	--layout=tagged install \
-	|| fail
-set +x
-
-
-printf "\nDONE the b2 boost build\n\n"
-
-# copy all boost includes for header only libraries
-find ./libs -maxdepth 6 -type d -print0 | while IFS= read -rd '' D; do
-	substr="include"
-	if  test "${D#*$substr}" != "$D" # looking for include dir's
-	then
-		end_of=$(echo $D | tail -c 8) # 8 = len(include) + end string char
-		#echo "$end_of"
-		if [ $end_of = $substr ]
-		then
-			cp -r "$D" ./mingw_build
-		fi
-	fi
-done
-
-popd
-
-else
-	printf "\n\nSkipping boost (as selected in options)\n\n"
-
-fi
+# ** building boost **
+pushd "${GALAXY_DIR}" || fail
+	contrib/gitian-descriptors/libboost-build/build-boost-multiarch || fail "Failed to build dependence - boost lib for ${TARGET_ARCH}"
+popd || fail
+echo "\nAll done regarding boost.\n"
 
 
 printf "\n\n=========================================================================\n\n"
 printf "libsodium...\n\n"
+cd "$HOME/build/" || fail "Can not enter build dir"
 
 if ((option_shell_in_sodium)) ; then
 	printf "\nSTARTING TEST BASH (in sodium), while in PWD=$PWD\n"
