build-boost-osx fix

diff --git a/contrib/gitian-descriptors/libboost-build/build-boost-osx b/contrib/gitian-descriptors/libboost-build/build-boost-osx
--- a/contrib/gitian-descriptors/libboost-build/build-boost-osx
+++ b/contrib/gitian-descriptors/libboost-build/build-boost-osx
@@ -11,7 +11,7 @@ printf "boost...\n\n"
 BOOST_DIR="$HOME/build/boost/"
 cd "$HOME/build/" || fail "Can not enter build dir"
 
-option_download_skip=1  # XXXXXXXXXXXXXXXXX
+option_download_skip=0  # XXXXXXXXXXXXXXXXX
 option_allow_boost=1
 
 if (( option_allow_boost )) ; then
@@ -63,13 +63,13 @@ git clean -xdf || fail
 rm -rf static-build || fail
 mkdir static-build || fail
 
-boost_user_gcc="/home/ubuntu/build/osxcross/target/bin//x86_64-apple-darwin15-clang++"
+boost_user_gcc="/home/ubuntu/build/osxcross/target/bin/x86_64-apple-darwin15-clang++"
 #boost_user_gcc=""
 printf "\n\nWill set boost user config to use compiler: (%s)\n" "$boost_user_gcc"
 
 printf "\n\nBoost build - main part (PWD=$PWD). ls:\n" ; ls ; printf "\n\n"
 echo "# This config was GENERATED (will be over-written) by $0." > user-config.jam || fail
-echo "using clang : 3.8.0 : $boost_user_gcc" >> user-config.jam || fail
+echo "using clang-darwin : 3.8.0 : $boost_user_gcc" >> user-config.jam || fail
 
 
   printf "\nTEST TOOLS (in BOOST script):\n"
@@ -105,9 +105,9 @@ set -x
 ./b2 \
     -q \
     "${b2_opt_debug[@]}" \
-    -a --user-config=user-config.jam toolset=clang variant=release \
+    -a --user-config=user-config.jam --toolset=darwin-4.2.1 variant=release \
     target-os=darwin \
-    --prefix=/"$BOOST_DIR"/osx-build threading=multi \
+    --prefix=/"$BOOST_DIR"/osx-build threadapi=pthread \
      "${b2_opt_with_lib[@]}" \
     -j 1 \
     -sNO_BZIP2=1 --sNO_ZLIB=1 \
@@ -129,7 +129,7 @@ find ./libs -maxdepth 6 -type d -print0 | while IFS= read -rd '' D; do
         #echo "$end_of"
         if [ $end_of = $substr ]
         then
-            cp -r "$D" ./static-build || fail "Can not copy $D"
+            cp -r "$D" ./osx-build || fail "Can not copy $D"
         fi
     fi
 done
