[gitian] integrate boost-multiarch for osx build

diff --git a/contrib/gitian-descriptors/libboost-build/build-boost-multiarch b/contrib/gitian-descriptors/libboost-build/build-boost-multiarch
--- a/contrib/gitian-descriptors/libboost-build/build-boost-multiarch
+++ b/contrib/gitian-descriptors/libboost-build/build-boost-multiarch
@@ -74,21 +74,35 @@ then
 			echo "Building boost libraries for TARGET='${TARGET_ARCH}'"
 
 			echo "# This config was GENERATED (will be over-written) by $0." > "${USER_CONFIG_FILE}" || fail
+			build_toolset="gcc"
+			link_type="shared"
 
 			if [[ $TARGET_ARCH == "x86_64-w64-mingw32" || $TARGET_ARCH == "i686-w64-mingw32" ]]
 			then
 				boost_user_gcc="${WRAP_DIR}/${TARGET_ARCH}-g++ ;"
 				build_target_os="windows"
-				# threadapi=win32 \ # is necessary?
-				link_type="shared"
 				echo "using gcc : 4.9.2 : ${boost_user_gcc}" >> "${USER_CONFIG_FILE}" || fail
+
 			elif [[ $TARGET_ARCH == "x86_64-linux-gnu" ]]
 			then
 				boost_user_gcc="${WRAP_DIR}/g++ ;"
 				build_target_os="linux"
 				link_type="static"
 				echo "using gcc : 5.4.0 : ${boost_user_gcc}" >> "${USER_CONFIG_FILE}" || fail
-			fi
+
+			elif [[ $TARGET_ARCH == "x86_64-apple-darwin15" ]]
+			then
+				boost_user_gcc="${WRAP_DIR}/x86_64-apple-darwin15-clang++-libc++"
+				build_target_os="darwin"
+				build_toolset="darwin --toolset-root=\"${BUILD_DIR}/osxcross/target/bin/\""
+				AR="${WRAP_DIR}/x86_64-apple-darwin15-ar"
+				LD="${WRAP_DIR}/x86_64-apple-darwin15-ld"
+				STRIP="${WRAP_DIR}/x86_64-apple-darwin15-strip"
+				RANLIB="${WRAP_DIR}/x86_64-apple-darwin15-ranlib"
+				printf "using darwin : : $boost_user_gcc : <linker-type>\"darwin\" <cxxflags>\"-arch x86_64 " >> "${USER_CONFIG_FILE}" || fail
+				printf "-std=c++14 -fvisibility=hidden -mmacosx-version-min=10.7 -march=core2 " >> "${USER_CONFIG_FILE}" || fail
+				printf "--sysroot=/${BUILD_DIR}/osxcross/target/SDK/MacOSX10.11.sdk\" <linkflags>\"\" " >> "${USER_CONFIG_FILE}" || fail
+				printf "<archiver>\"$AR\" <striper>\"$STRIP\" <ranlib>\"$RANLIB\" :  ;\n" >> "${USER_CONFIG_FILE}" || fail
 		fi
 	fi
 
@@ -124,7 +138,7 @@ then
 			--prefix="${BOOST_BUILD_DIR}" \
 			--user-config="${USER_CONFIG_FILE}" \
 			"${b2_opt_with_lib[@]}" \
-			toolset=gcc \
+			toolset="${build_toolset}" \
 			target-os="${build_target_os}" \
 			--build-type=complete \
 			variant=release \
@@ -137,7 +151,12 @@ then
 					set -x
 					fail "The b2 build of boost failed"
 				}
-	set +x
+		set +x
+
+		# Other may useful b2 options
+		# architecture=x86 address-model=64 --arch=x86_64
+		# boost.locale.icu=off boost.locale.iconv=on
+		# threadapi=win32
 
 		printf "\n\nDONE the b2 boost build\n\n"
 
