[gitian] some fixes in multiarch boost building

diff --git a/contrib/gitian-descriptors/libboost-build/build-boost-multiarch b/contrib/gitian-descriptors/libboost-build/build-boost-multiarch
--- a/contrib/gitian-descriptors/libboost-build/build-boost-multiarch
+++ b/contrib/gitian-descriptors/libboost-build/build-boost-multiarch
@@ -3,12 +3,16 @@
 set -o errexit
 set -o nounset
 
-# Variables required from parent script:
+# Variables/Fuctions required from parent script:
 # TARGET_ARCH
 # BUILD_DIR
 # WRAP_DIR
+# BOOST_BUILD_DIR
+# fail function
+
 readonly BOOST_BUILD_THREADS=2
 readonly BOOST_DIR="${BUILD_DIR}/boost"
+readonly USER_CONFIG_FILE="${BOOST_DIR}/user-config.jam"
 
 # option_download_skip
 # option_allow_boost
@@ -38,45 +42,14 @@ else
 fi
 
 
-# Setting target depends optins
-if [ -v ${TARGET_ARCH+x} ]
-then
-	echo "Require TARGET_ARCH variable not set, exiting/failing"
-	fail
-else
-	echo "Building boost libraries for TARGET='${TARGET_ARCH}'"
-
-
-	echo "# This config was GENERATED (will be over-written) by $0." > user-config.jam || fail
-
-	boost_user_gcc="${WRAP_DIR}/${TARGET_ARCH}-g++ ;"
-	echo "using gcc : 4.9.2 : $boost_user_gcc" >> user-config.jam || fail
-
-	if [[ $TARGET_ARCH == "x86_64-w64-mingw32" ]]; then
-		:
-	elif  [[ $TARGET_ARCH == "i686-w64-mingw32" ]]; then
-		:
-	fi
-fi
-
-# Checking build directories
-if [ -v ${BOOST_DIR+x} ]
-then
-	echo "Require BOOST_DIR variable not set, exiting/failing"
-	fail
-else
-	echo "Building boost in BOOST_DIR='${BOOST_DIR}'"
-	readonly BOOST_BUILD_DIR="${TARGET_ARCH}-build"
-fi
-
 # Main download and build
 if (( option_allow_boost ))
 then
-	printf "\n\nWill build boost now\n\n"
+	printf "\n\nWill building boost in BOOST_DIR='${BOOST_DIR}', OUTPUT_DIR='${BOOST_BUILD_DIR}'\n\n"
 
 	if (( option_download_skip ))
 	then
-		printf "\n\n\n\nSkipping download (boost)\n\n\n\n"
+		printf "\n\nSkipping download (boost)\n\n"
 
 	else
 		# Download main boost repository
@@ -85,6 +58,27 @@ then
 			# Download boost submodules in n=3 attempts
 			dl_boost_submodules_n 3
 		popd
+
+		# Setting target depends optins
+		if [ -v ${TARGET_ARCH+x} ]
+		then
+			echo "Require TARGET_ARCH variable not set, exiting/failing"
+			fail
+		else
+			echo "Building boost libraries for TARGET='${TARGET_ARCH}'"
+
+
+			echo "# This config was GENERATED (will be over-written) by $0." > "${USER_CONFIG_FILE}" || fail
+
+			boost_user_gcc="${WRAP_DIR}/${TARGET_ARCH}-g++ ;"
+			echo "using gcc : 4.9.2 : $boost_user_gcc" >> "${USER_CONFIG_FILE}" || fail
+
+			if [[ $TARGET_ARCH == "x86_64-w64-mingw32" ]]; then
+				:
+			elif  [[ $TARGET_ARCH == "i686-w64-mingw32" ]]; then
+				:
+			fi
+		fi
 	fi
 
 	pushd boost || fail # cd
@@ -116,8 +110,8 @@ then
 			"${b2_opt_debug[@]}" \
 			-a \
 			-j "${BOOST_BUILD_THREADS}" \
-			--prefix=/"$BOOST_DIR"/mingw_build \
-			--user-config=user-config.jam \
+			--prefix="${BOOST_BUILD_DIR}" \
+			--user-config="${USER_CONFIG_FILE}" \
 			"${b2_opt_with_lib[@]}" \
 			toolset=gcc \
 			target-os=windows \
